### ISSUE TITLE
Unable to execute Linux binary

### ISSUE THREAD

**Issue by wuffi** [hnolCol/instantclue#8]
The binary for Microsoft Windows works very well on a recent 64-bit Desktop and is a pleasure to use.
Trying to run the file instant_clue for Linux on a X60 Thinkpad (32-bit) with Ubuntu 16.04 gives me the following error message:

    bash: ./instant_clue: cannot execute binary file: Exec format error

I think this could be due to the fact that the binary file is actually for 64-bit, not for 32-bit. It could be helpful to add this information in the README or Download page, if this is the case.

In order to still be able to run instant clue, I cloned the repository and tried invoked

    python3 instant_clue.py

(assuming that the file runs with Python 3 and not 2; if this is the case, it could be helpful to mention this information in the README).
This gives me the following error message (I omit the traceback and show the last line only):

    ImportError: No modules named 'matplotlib._color_data'

Here, I got a bit stuck, because at least I have installed the package `python3-matplotlib`.

**Comment by hnolCol** [comment]
Thanks for the good points about changing the readme. Implemented that. 
Could you do me a favour and check if the command
`from matplotlib._color_data import TABLEAU_COLORS` 
works from Python IDLE?
The line that causes this error is in the utils.py module. Trying to delete this line will cause an error in line 157. 
Therfore, try to change. If this works on your paltform you can either make a pull request or just let me know and I will incorporate it. Thank you for your help: 
```python
from matplotlib._color_data import TABLEAU_COLORS,XKCD_COLORS,CSS4_COLORS
```
To
```python
try:  
    from matplotlib._color_data import TABLEAU_COLORS,XKCD_COLORS,CSS4_COLORS 
except: 
    TABLEAU_COLORS,XKCD_COLORS,CSS4_COLORS = dict(), dict(), dict()```

**Comment by wuffi** [comment]
Thanks a lot for your help.
Now I get the following error message:

    AttributeError: module 'matplotlib.colors' has no attribute 'get_named_colors_mapping'

**Comment by hnolCol** [comment]
InstantClue Windows binaries are build with matplotlib 3.0.1. 
Which version do you have? At least worth a try updating with pip3.  Sounds like a matplotlib version problem to me.

**Comment by wuffi** [comment]
Thanks a lot for your feedback.  
I finally managed to get *Instant Clue* running after upgrading the 32-bit machine to Ubuntu 18 and installing current versions of the required Python modules using `pip3`.  
I think the issue really is that the Python packages on Ubuntu quickly become outdated and it makes a lot of sense to get current versions in parallel using `pip3`.  
What might be handy is to have also *Instant Clue* as a `pip3` package, but I know it's easier said than done.
